// CourseActionType.js
export const FETCH_COURSES_LOADING = 'FETCH_COURSES_LOADING';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

// CourseActionType.js
export const FETCH_COURSE_LOADING = 'FETCH_COURSE_LOADING';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE';





