export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAILURE = "ENROLL_COURSE_FAILURE";

export const FETCH_ENROLLED_COURSES_REQUEST = "FETCH_ENROLLED_COURSES_REQUEST";
export const FETCH_ENROLLED_COURSES_SUCCESS = "FETCH_ENROLLED_COURSES_SUCCESS";
export const FETCH_ENROLLED_COURSES_FAILURE = "FETCH_ENROLLED_COURSES_FAILURE";
